### ISSUE TITLE
Problem after the installation/Close suddenly

### ISSUE THREAD

**Issue by BrecAurelie** [johndempster/WinWCPXE#1]
Hello, thank you very much for proposing a free software for patch clamp! 
However I'm having a trouble using it. I followed the instruction for the installation (enter my amplifier and my laboratory interface) but as soon as I go to Record>Pipette Seal Test / Signal Monito, the software close suddently. I've done it several times (with or without firewalls) but it keeps closing. Do you have any idea why I have this problem?

**Comment by johndempster** [comment]
Hi, Sorry I hadn't noticed this message before (most users with problems contact me on j,dempster@strath.ac.uk). Do you happen to be using an Axon Digidata 1440A interface unit? A number of users have recently experienced similar problems to you. The problem seems to be an incompatibility between the PCLAMP V11 drivers, Windows 10 and WinWCP. A solution to the problem is remove PCLAMP 11.X and install  PCLAMP 10.7.

**Comment by BrecAurelie** [comment]
Hi! No worries, thanks a lot for your reply! Yes absolutely I'm using a Axon Digidata 1440A digitizer and Windows 10 (I should have mentionned that in my first message actually). I'm gonna try with PCLAMP 10.7 drivers instead, thank you very much!
